export { counterWidgetDefinition } from "./counter.js";
export { clockWidgetDefinition } from "./clock.js";
export { imageWidgetDefinition } from "./image.js";
export { customHtmlWidgetDefinition } from "./customHtml.js";
export { marqueeWidgetDefinition } from "./marquee.js";
export { shapeWidgetDefinition } from "./shape.js";
export { soundboardWidgetDefinition } from "./soundboard.js";
export { textWidgetDefinition } from "./text.js";
export { timerWidgetDefinition } from "./timer.js";
